### PR TITLE
Use GraphQL Code Generator and Apollo Angular template

### PR DESCRIPTION
**Pull request by kamilkisiela**
Adds apollo-angular template of GraphQL Code Generator to produce strongly typed services with more convenient API and to fully experience IDE's support for GraphQL (thanks to having .graphql files)

It's a work in progress because I don't know if you want something like this, @vsavkin ?

---

```typescript
return this.apollo.query({
  query: gql`
    query($path: String!, $collection: String!, $schematic: String!) {
      workspace(path: $path) {
        schematicCollections(name: $collection) {
          schematics(name: $schematic) {
            collection
            name
            description
            schema {
              name
              enum
              type
            }
          }
        }
      }
    }
  `,
  variables: p
});
```

Turns into `.graphql` file with autocompletion, validation etc:

```graphql
query($path: String!, $collection: String!, $schematic: String!) {
  workspace(path: $path) {
    schematicCollections(name: $collection) {
      schematics(name: $schematic) {
        collection
        name
        description
        schema {
          name
          enum
          type
          description
          defaultValue
          required
          positional
        }
      }
    }
  }
}
```

and strongly typed service, just for that query:

```typescript
return this.getSchematicGQL.fetch(p);
```

---

More on that here:

- [Publication](https://medium.com/the-guild/apollo-angular-code-generation-7903da1f8559)
- [Chapter in docs](https://www.apollographql.com/docs/angular/basics/services.html#Code-Generation)

### CODE REVIEW

**Comment by vsavkin** [comment]
It looks interesting. 

Is there a way to somehow annotate or name generated files to make it clear that they aren't written by hand?

For instance, the name and the content of `feature-generate/src/lib/graphql/index.ts` don't really reveal it's generated.

**Comment by kamilkisiela** [comment]
@vsavkin You can customize the name of the output file

**Comment by mrmeku** [comment]
@kamilkisiela Is there anything I can do to help you finish up this PR? I'm really excited to start using it so whatever you need I'd love to help with!

**Comment by kamilkisiela** [comment]
@mrmeku I can finish it tomorrow :) Just waiter for 👍 from you guys :)

**Comment by kamilkisiela** [comment]
@mrmeku done

**Comment by kamilkisiela** [comment]
@vsavkin now the file's path says it's generated, tests are good.

**Comment by mrmeku** [comment]
@kamilkisiela So excited to use this. The front end code looks so much cleaner with it than without it. Thanks again for being awesome!

**Pull request merged**
