### PR TITLE
Renovate

### PR DESCRIPTION
**Pull request by kamilkisiela**
[We](https://github.com/the-guild-org) use renovate in all of our projects, super helpful to update dependencies. One PR per monorepos, for example: `@angular/{core, common, browser, ...}` are gathered together.

I configured it to auto merge every PR that bumps a dependency to patch or minor version, the major ones has to be reviewed.

One thing after merging the PR would be to activate RenovateApp on this repository.

### CODE REVIEW

**Comment by mrmeku** [comment]
@kamilkisiela Thanks so much for coding this up for us! Would renovate run our full CI sweet before merging minor version bumps? I think if we had that guarantee then this change would be sufficiently safe to merge.

**Comment by kamilkisiela** [comment]
@mrmeku Yes, it waits for CI to go 💚

**Comment by kamilkisiela** [comment]
But only if you have `ci/circleci` check marked as required in GitHub settings

**Comment by mrmeku** [comment]
@kamilkisiela Would you mind rebasing/squashing your commits into one prior to merging? I had to rewrite history a bit after merging you last PR because I forgot to have you do that before I merged :p

**Comment by kamilkisiela** [comment]
@mrmeku I resolved conflicts, can't you just squash them?

**Pull request merged**
