### PR TITLE
perf(projects): Improve rendering performance

### PR DESCRIPTION
**Pull request by mrmeku**

### CODE REVIEW

**Comment by isaacplmann** [comment]
I don't think this is what you wanted:
image

Also, I don't see the animations working on the projects screen.

**Comment by mrmeku** [comment]
@isaacplmann I removed the animations (they were broken). This is ready for another look now that its less buggy

**Comment by isaacplmann** [comment]
@mrmeku I think I was doing something wrong when I was spinning up the PR to view in the browser.  It looks better now, but i can't get the recent actions list to ever change.

**Comment by isaacplmann** [comment]
It looks like the recent actions are only broken for `test` and `lint` actions.  But it wasn't caused by this PR.

**Pull request merged**
