### PR TITLE
feat: add schematics-docker extension

### PR DESCRIPTION
**Pull request by Gillespie59**

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you for the PR. Please run `yarn start format` to fix the CI, and then I'll merge it.

**Comment by vsavkin** [comment]
@Gillespie59 could you run the format command?

**Comment by Gillespie59** [comment]
I'll run it when I back from holidays. (Tomorrow :) )

**Comment by Gillespie59** [comment]
I do not understand why the e2e tests are not working. Any ideas ?

**Comment by mrmeku** [comment]
@Gillespie59 I think if you rebase and push again the e2e tests will pass now. I've done a bit of work this past week to make them run more reliably

**Pull request closed without merging**
